### ISSUE TITLE
Jug script is not installed

### ISSUE THREAD

**Issue by luispedro** [conda-forge/jug-feedstock#1]
This package installs the library, but not the `jug` script (`entry_point`).

**Comment by ocefpaf** [comment]
The `entry_point` is specified in https://github.com/conda-forge/jug-feedstock/blob/master/recipe/meta.yaml#L19 and tested in https://github.com/conda-forge/jug-feedstock/blob/master/recipe/meta.yaml#L35

Can you provide more details? Maybe the `noarch` is the culprit here...

**Comment by luispedro** [comment]
I also don't understand why it does not work, but the `tar.bz2` file at https://anaconda.org/conda-forge/jug does not include anything in `bin`.

**Comment by ocefpaf** [comment]
> I also don't understand why it does not work, but the `tar.bz2` file at https://anaconda.org/conda-forge/jug does not include anything in `bin`.

My understanding is that conda will create it during the installation, can you try:

```
conda create --name TEST jug
source activate TEST
jug -h
```

**Comment by luispedro** [comment]
Ok, figured this out: It works, but only on more recent versions of conda.
